config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  resources :events do
    resources :guests
    resources :tasks
    resources :categories, only: [:create]
    resources :expenses
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :guests, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :categories, dependent: :destroy

   # Validations
   validates :name, presence: true
   validates :date, presence: true
   validates :event_type, presence: true
   validates :user, presence: true
   validates :estimated_guests, presence: true, numericality: { greater_than: 0 }

   # Custom validation for date
   validate :date_cannot_be_in_the_past

   private

   def date_cannot_be_in_the_past
     if date.present? && date < Date.today
       errors.add(:date, "cannot be in the past")
     end
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :event_type, :estimated_guests, :description)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Event type:</strong>
    <%= event.event_type %>
  </p>

  <p>
    <strong>Estimated guests:</strong>
    <%= event.estimated_guests %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= event.user_id %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :event_type, style: "display: block" %>
    <%= form.text_field :event_type %>
  </div>

  <div>
    <%= form.label :estimated_guests, style: "display: block" %>
    <%= form.number_field :estimated_guests %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<h1>Your Wedding Events</h1>
<%= link_to 'Create New Event', new_event_path, class: 'btn btn-primary' %>

<!-- Display all events here -->
<% @events.each do |event| %>
  <div>
    <h3><%= event.name %></h3>
    <p><%= event.description %></p>
    <%= link_to 'Show', event_path(event) %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><strong>Dates:</strong> <%= @event.date %></p>
<p><strong>Type de réception:</strong> <%= @event.event_type %></p>
<p><strong>Nombre d'invités estimé:</strong> <%= @event.estimated_guests %></p>
<p><strong>À propos:</strong> <%= @event.description %></p>

<h3>Organisation</h3>
<ul>
  <li><%= link_to "Les invités", event_guests_path(@event) %></li>
  <li><%= link_to "Les missions", event_tasks_path(@event) %></li>
  <li><%= link_to "Les dépenses", event_expenses_path(@event) %></li>
</ul>

<%= link_to 'Modifier mon mariage', edit_event_path(@event) %> |
<%= link_to 'Retour', events_path %> |
<%= button_to 'Supprimer cet évènement', @event, method: :delete, data: { confirm: 'Are you sure?' } %>